name: Antelope CDT

on: [push]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Antelope CDT
        run: wget https://github.com/AntelopeIO/cdt/releases/download/v3.1.0-rc1/cdt_3.1.0-rc1_amd64.deb && sudo apt install ./cdt_3.1.0-rc1_amd64.deb

       
      - uses: actions/checkout@v2
      - name: Compile WASM
        run: ./.github/scripts/build.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cetf.abi
            cetf.wasm
